Feature/banking data
ConsumerDataStandardsAustralia/dsb-test-data pull request #14
Opened 2024-04-25 03:44 UTC by tom-schier

- Added hosting of banking data
- updated to use v1.29.1 dataset

2024-04-25 23:38 UTC, vadkor commented on test-data-server/src/services/database.interface.ts
Why did you comment out all the methods in the interface?

2024-04-25 23:39 UTC, vadkor commented on test-data-server/src/services/single-banking.service.ts
What is the purpose of this? It doesn't have a single line of code.

2024-04-25 23:49 UTC, vadkor commented on test-data-server/data/endpoints.json
Only the /common/customer/detail endpoint?

2024-04-25 23:59 UTC, vadkor commented on test-data-server/postman/1.29.1/WIP - Energy.postman_environment.json
I don't think it's OK to have WIP in file names.

2024-04-26 00:01 UTC, vadkor commented on test-data-server/postman/1.29.1/WIP - Energy.postman_environment.json
Are we creating version number-named subfolders again?

2024-04-26 00:05 UTC, vadkor commented on load-test-data/input/1.26.0/all-data/banking-accounts.json
Why did you add this file to folder 1.26.0? Why do we have this folder? Why do we have this file - it's not referenced anywhere?

2024-04-26 00:09 UTC, vadkor commented on load-test-data/input/1.26.0/all-data/complete-data.json
We have this huge file here and in utils/data. This is not a good idea.

2024-04-26 00:30 UTC, vadkor commented
Overall, the code make an impression of an unfinished work. A lot of commented out blocks or WIPs. Should be cleaned up. Also, I don't approve such a great number of commits. It looks more like an undo history to me rather than a history of changes worth keeping in the repository. It could have its use cases a few years back, but now that VSCode and other IDEs have local file save histories, it's just a pollution of the SCM log. The WIP commits are only needed if you want to switch to another branch and stashing is not favoured for some reason. I would recommend squashing the commits when this PR is merged.

2024-04-26 23:11 UTC, tom-schier commented on test-data-server/data/endpoints.json
The app is now using the default defintions from the @cds-au/holder-sdk, ie implemention all endpoints for banking and energy. For the common endpoint. For the common API we only implement the two endpoints in the file.

2024-04-26 23:12 UTC, tom-schier commented on test-data-server/src/services/single-banking.service.ts
Will be deleted.

2024-04-26 23:51 UTC, tom-schier commented on test-data-server/postman/1.29.1/WIP - Energy.postman_environment.json
Currently you can read in different versions of data. Each data set has its own set of ids. The files in here are there to make it easier use with PM collection as they contain the ids for accounts, service points, etc for each data set.

2024-04-27 00:01 UTC, tom-schier commented on test-data-server/postman/1.29.1/WIP - Energy.postman_environment.json
I have restructured / renamed the PM environment files , data files etc. This should now be more obvious.

2024-04-27 00:04 UTC, tom-schier commented on load-test-data/input/1.26.0/all-data/complete-data.json
Deleted

2024-04-27 00:06 UTC, tom-schier commented on load-test-data/input/1.26.0/all-data/banking-accounts.json
This particular file will be deleted.

2024-04-27 00:08 UTC, tom-schier commented on test-data-server/src/services/database.interface.ts
There has been a fundamental restructure of the classes and interfaces. Happy to discuss. The file has since changed

2024-05-06 02:40 UTC, sumayahasancds requested changes
It looks like there's some more commented-out code in this pull request. 
- ⁠load-test-data/src/app.ts Line 88-89
- ⁠test-data-server/src/modules/auth-service.ts Line 136,140, 142
- ⁠utils/src/create-pm-environment-file.ts 143-150

Could you please provide some context or comments explaining why these are retained? If it's no longer needed or the purpose of the commented-out code isn't clear, it might be best to remove it to keep the codebase clean and maintainable. If we find we need it later, we can always retrieve it from the version history. 

Alternatively, If there’s a reason to keep it, such as a potential future use, please document that clearly above the commented-out section. 

Thank you!

2024-05-06 23:18 UTC, sumayahasancds approved these changes

2024-05-07 07:27 UTC, merged